### ISSUE TITLE
Cluster-autoscaler crashing after new input-manifest has been applied

### ISSUE THREAD

**Issue by Danielss89** [berops/claudie#1109]
I've applied my input-manifest for the first time, but now the cluster-autoscaler is crashing:
```
I1122 21:28:49.463186       1 leaderelection.go:248] attempting to acquire leader lease kube-system/cluster-autoscaler...
I1122 21:28:49.474188       1 leaderelection.go:258] successfully acquired lease kube-system/cluster-autoscaler
I1122 21:28:49.513296       1 node_instances_cache.go:156] Start refreshing cloud provider node instances cache
I1122 21:28:49.526418       1 node_instances_cache.go:168] Refresh cloud provider node instances cache finished, refresh took 13.102415ms
W1122 21:28:59.522599       1 clusterstate.go:428] AcceptableRanges have not been populated yet. Skip checking
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x3cfca79]

goroutine 76 [running]:
k8s.io/autoscaler/cluster-autoscaler/simulator/scheduling.(*HintingSimulator).findNode(0xc000c4a888, 0x5a2fdc0?, {0x5a2fdc0, 0xc0002b31d0}, 0xc000c96c00, 0x0?)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/simulator/scheduling/hinting_simulator.go:114 +0x159
k8s.io/autoscaler/cluster-autoscaler/simulator/scheduling.(*HintingSimulator).TrySchedulePods(0x40a5c00?, {0x5a2fdc0, 0xc0002b31d0}, {0xc0000127f0, 0x1, 0xc0005b3488?}, 0x4519
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/simulator/scheduling/hinting_simulator.go:70 +0x2cf
k8s.io/autoscaler/cluster-autoscaler/core/podlistprocessor.(*filterOutSchedulablePodListProcessor).filterOutSchedulableByPacking(0xc0002b31f0, {0xc0000127f0, 0x1, 0x1}, {0x5a2
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/podlistprocessor/filter_out_schedulable.go:101 +0x111
k8s.io/autoscaler/cluster-autoscaler/core/podlistprocessor.(*filterOutSchedulablePodListProcessor).Process(0x0?, 0xc000894c00, {0xc0000127f0?, 0x1, 0x1})
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/podlistprocessor/filter_out_schedulable.go:66 +0xd5
k8s.io/autoscaler/cluster-autoscaler/core/podlistprocessor.(*defaultPodListProcessor).Process(0xc000c7a170, 0xc00101d3e0?, {0xc0000127f0?, 0x5?, 0x5?})
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/podlistprocessor/pod_list_processor.go:45 +0x65
k8s.io/autoscaler/cluster-autoscaler/core.(*StaticAutoscaler).RunOnce(0xc000c7c960, {0xc14fba86dea63fcf?, 0x25a6e4bf4?, 0x87e1e20?})
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/static_autoscaler.go:477 +0x1ca3
main.run(0xc0005cb600?, {0x5a277b8, 0xc000aa47b0})
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:442 +0x2cd
main.main.func2({0x8b9dc6?, 0xc0000f9e00?})
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:529 +0x25
created by k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:211 +0x11b
Stream closed EOF for claudie/autoscaler-wox-cluster-fxb27c5-6fdd896ccd-lfqjl (cluster-autoscaler)
```

**Comment by Danielss89** [comment]
After the night, the autoscaler is now up again. I don't know if we should just close this issue, or you want to look further into it?

**Comment by cloudziu** [comment]
Hey @Danielss89 thank you for submitting the issue.
In the `autoscaler-$CLUSTER_ID` pod there are two containers. The one that is CrashLooping is from the Kubernetes upstream repo. The bug you are encountering is related to [this issue](https://github.com/kubernetes/autoscaler/issues/5825). 
You can upgrade the autoscaler deployment image to `image: registry.k8s.io/autoscaling/cluster-autoscaler:v1.26.1`
The second option is to deploy the cluster with Kubernetes version `v1.26.1`, because the cluster-autoscaler version is aligned with the K8s version.

**Comment by cloudziu** [comment]
You should be able to update by changing the version.
https://docs.claudie.io/v0.6.2/update/update/#updating-kubernetes-version
For now I will close this issue as completed 😄
